export const NSW_VENUES = [
  { name: "Batemans Bay Tennis Courts", slug: "BatemansBayTennisCourts", suburb: "Batemans Bay" },
  { name: "Bega Tennis Club", slug: "BegaTennisClub", suburb: "Bega" },
  { name: "Byrnes Street Tennis Courts", slug: "ByrnesStreetTennisCourts", suburb: "South Granville" },
  { name: "Casino Town Tennis Club", slug: "CasinoTownTennisClub", suburb: "Casino" },
  { name: "Central Gardens Tennis Courts", slug: "CentralGardensTennisCourts", suburb: "Greystanes" },
  { name: "Civic Park Tennis Courts", slug: "CivicParkTennisCourts", suburb: "Pendle Hill" },
  { name: "Copacabana Tennis Club", slug: "CopacabanaTennisClub", suburb: "Copacabana" },
  { name: "Cowra Tennis Club", slug: "CowraTennisClub", suburb: "Cowra" },
  { name: "Dirrabarri Tennis Courts", slug: "DirrabarriTennisCourts", suburb: "Pemulwuy" },
  { name: "Fullagar Road Tennis Courts", slug: "FullagarRoadTennisCourts", suburb: "Wentworthville" },
  { name: "Greystanes Sportsground Tennis Courts", slug: "GreystanesSportsgroundTennisCourts", suburb: "Greystanes" },
  { name: "Griffith Tennis Club", slug: "GriffithTennisClub", suburb: "Griffith" },
  { name: "Guildford West Sports Ground", slug: "GuildfordWestSportsGround", suburb: "Guildford West" },
  { name: "Hinton and District Tennis Club", slug: "HintonAndDistrictTennisClub", suburb: "Hinton" },
  { name: "Lambton Park Tennis Club", slug: "LambtonParkTennisClub", suburb: "Lambton" },
  { name: "Lawson Square Park Tennis Courts", slug: "LawsonSquareParkTennisCourts", suburb: "Merrylands" },
  { name: "Merrylands Park Tennis Courts", slug: "MerrylandsParkTennisCourts", suburb: "Merrylands" },
  { name: "Paramount Tennis Club Dubbo", slug: "Paramounttennisclubdubbo", suburb: "Dubbo" },
  { name: "Parkes Tennis Club", slug: "ParkesTennisClub", suburb: "Parkes" },
  { name: "Soldiers Point Tennis Club", slug: "SoldiersPointTennisClub", suburb: "Soldiers Point" },
  { name: "Tilligerry Tennis Club", slug: "TilligerryTennisClub", suburb: "Mallabula" },
  { name: "Tyneside Tennis Courts", slug: "TynesideTennisCourts", suburb: "Willoughby" },
  { name: "Wagga Wagga Tennis Association", slug: "WaggaWaggaTennisAssociation", suburb: "Wagga Wagga" },
  { name: "Wyong District Tennis Association", slug: "WyongDistrictTennisAssociation", suburb: "Wyong" },
];

export const HILLS_VENUES = [
  { name: "Annangrove Reserve Tennis Courts", venueId: 15, suburb: "Annangrove" },
  { name: "Balmoral Reserve Tennis Courts", venueId: 80, suburb: "Kellyville" },
  { name: "Bella Vista Tennis Courts", venueId: 17, suburb: "Bella Vista" },
  { name: "Bernie Mullane Tennis Courts", venueId: 20, suburb: "Kellyville" },
  { name: "Crestwood Reserve Tennis Courts", venueId: 31, suburb: "Baulkham Hills" },
  { name: "Gables Central Playing Fields Tennis Courts", venueId: 87, suburb: "Box Hill" },
  { name: "Kenthurst Park Tennis Courts", venueId: 25, suburb: "Kenthurst" },
  { name: "Les Shore Reserve Tennis Courts", venueId: 23, suburb: "Glenorie" },
  { name: "Ted Horwood Reserve Tennis Courts", venueId: 19, suburb: "Baulkham Hills" },
];
